// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6_N7KbMj-ZUazQh3CpnSN2iSyCnaJnTY',
    appId: '1:470199704264:web:ecf67141f6e0615a50a3fd',
    messagingSenderId: '470199704264',
    projectId: 'last-last-66340',
    authDomain: 'last-last-66340.firebaseapp.com',
    storageBucket: 'last-last-66340.appspot.com',
    measurementId: 'G-97TB3RN0L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_Fw550eB-cOQlJ0tYA-eUSLdi2OQ9mk',
    appId: '1:470199704264:android:070035e9ea2cb92650a3fd',
    messagingSenderId: '470199704264',
    projectId: 'last-last-66340',
    storageBucket: 'last-last-66340.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoPHjtLlvJLCEg64eTM3zx-G-14oBW0aA',
    appId: '1:470199704264:ios:3928104092ec8db050a3fd',
    messagingSenderId: '470199704264',
    projectId: 'last-last-66340',
    storageBucket: 'last-last-66340.appspot.com',
    androidClientId: '470199704264-8elks3g5f9am73uqp2qqfj5pqrca7if3.apps.googleusercontent.com',
    iosClientId: '470199704264-p1utmm2781rldotmt0pic2ns3usf0fm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.maibon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoPHjtLlvJLCEg64eTM3zx-G-14oBW0aA',
    appId: '1:470199704264:ios:3b6ce427b63af3a950a3fd',
    messagingSenderId: '470199704264',
    projectId: 'last-last-66340',
    storageBucket: 'last-last-66340.appspot.com',
    androidClientId: '470199704264-8elks3g5f9am73uqp2qqfj5pqrca7if3.apps.googleusercontent.com',
    iosClientId: '470199704264-bsvrtqcv9pemsbkc0poj987lkbikgqof.apps.googleusercontent.com',
    iosBundleId: 'com.example.maibon.RunnerTests',
  );
}
